services:

  db:
    image: postgres:16

    environment:
      POSTGRES_DB: coursesdb
      POSTGRES_USER: coursesuser
      POSTGRES_PASSWORD: coursespass

    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .

    ports:
      - "8000:8000"

    env_file:
      - .env

    depends_on:
      - db

    volumes:
      - .:/app
      - ./media:/app/media

volumes:
  postgres_data:
